// Generated by Haxe 3.4.7
(function ($global) { "use strict";
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var BSHead = function() {
	this.bitIndex = 0;
	this.blockIndex = 0;
};
BSHead.__name__ = true;
BSHead.prototype = {
	read: function(data) {
		if(data.length <= this.blockIndex) {
			return haxe_ds_Option.None;
		} else {
			return haxe_ds_Option.Some((data[this.blockIndex] >> this.bitIndex & 1) == 1);
		}
	}
	,write: function(data,value) {
		while(data.length <= this.blockIndex) data.push(0);
		if(value) {
			data[this.blockIndex] |= 1 << this.bitIndex;
		}
	}
	,increment: function() {
		this.bitIndex += 1;
		if(this.bitIndex > 5) {
			this.bitIndex = 0;
			this.blockIndex += 1;
		}
	}
	,__class__: BSHead
};
var BSWriter = function() {
	this.head = new BSHead();
	this.data = [];
};
BSWriter.__name__ = true;
BSWriter.prototype = {
	toString: function() {
		var str = "";
		var _g = 0;
		var _g1 = this.data;
		while(_g < _g1.length) {
			var digit = _g1[_g];
			++_g;
			str += haxe_crypto_Base64.CHARS.charAt(digit);
		}
		return str;
	}
	,writeInt: function(value,bits) {
		var _g1 = 0;
		var _g = bits;
		while(_g1 < _g) {
			var i = _g1++;
			this.write([(value >> i & 1) == 1]);
		}
	}
	,write: function(values) {
		var _g = 0;
		while(_g < values.length) {
			var value = values[_g];
			++_g;
			this.head.write(this.data,value);
			this.head.increment();
		}
	}
	,__class__: BSWriter
};
var BSReader = function(encoded) {
	this.head = new BSHead();
	this.data = [];
	var _g1 = 0;
	var _g = encoded.length;
	while(_g1 < _g) {
		var i = _g1++;
		this.data.push(this.charToInt(encoded.charAt(i)));
	}
};
BSReader.__name__ = true;
BSReader.prototype = {
	charToInt: function($char) {
		var _g = 0;
		while(_g < 64) {
			var i = _g++;
			if(haxe_crypto_Base64.CHARS.charAt(i) == $char) {
				return i;
			}
		}
		throw new js__$Boot_HaxeError("base64 out of bounds");
	}
	,read: function(length) {
		var bits = [];
		var _g1 = 0;
		var _g = length;
		while(_g1 < _g) {
			var i = _g1++;
			var _g2 = this.head.read(this.data);
			switch(_g2[1]) {
			case 0:
				var bit = _g2[2];
				bits.push(bit);
				break;
			case 1:
				return haxe_ds_Option.None;
			}
			this.head.increment();
		}
		return haxe_ds_Option.Some(bits);
	}
	,readInt: function(length) {
		var _g = this.read(length);
		switch(_g[1]) {
		case 0:
			var bits = _g[2];
			var sum = 0;
			var _g1 = 0;
			var _g2 = length;
			while(_g1 < _g2) {
				var i = _g1++;
				sum += (bits[i] ? 1 : 0) << i;
			}
			return haxe_ds_Option.Some(sum);
		case 1:
			return haxe_ds_Option.None;
		}
	}
	,__class__: BSReader
};
var PlayControl = function() {
	this.speed = 1;
	this.paused = false;
	this.frame = 0;
};
PlayControl.__name__ = true;
PlayControl.prototype = {
	__class__: PlayControl
};
var Engine = function() {
	this.fakeTime = 0;
	this.pausedCallback = haxe_ds_Option.None;
	this.slot = new Video();
	this.recording = new VideoRecorder();
	this.playback = haxe_ds_Option.None;
	this.control = new PlayControl();
	var _gthis = this;
	this._requestAnimationFrame = ($_=window,$bind($_,$_.requestAnimationFrame));
	this._now = ($_=window.performance,$bind($_,$_.now));
	window.requestAnimationFrame = $bind(this,this.requestAnimationFrame);
	window.performance.now = function() {
		return _gthis.fakeTime;
	};
	window._keyup = $bind(this,this.keyup);
	window._keydown = $bind(this,this.keydown);
	this.fakeTime = this._now();
};
Engine.__name__ = true;
Engine.prototype = {
	requestAnimationFrame: function(callback) {
		var _gthis = this;
		var _g = this.playback;
		switch(_g[1]) {
		case 0:
			var player = _g[2];
			this.triggerPlayback(player);
			break;
		case 1:
			break;
		}
		this.fakeTime += 17;
		this.control.frame += 1;
		if(!this.control.paused) {
			var cb = function() {
				callback(_gthis.fakeTime);
			};
			var _g1 = this.control.speed;
			switch(_g1) {
			case 0:
				window.setTimeout(cb,null,0.1);
				break;
			case 1:
				this._requestAnimationFrame(cb);
				break;
			default:
				window.setTimeout(cb,0);
			}
		} else {
			this.pausedCallback = haxe_ds_Option.Some(callback);
		}
	}
	,triggerPlayback: function(player) {
		var _g = 0;
		var _g1 = player.getActions(this.control.frame);
		while(_g < _g1.length) {
			var action = _g1[_g];
			++_g;
			this.sendGameInput(action.code,action.down);
		}
		if(player.done(this.control.frame)) {
			this.playback = haxe_ds_Option.None;
		}
	}
	,triggerPausedCallback: function() {
		var _g = this.pausedCallback;
		switch(_g[1]) {
		case 0:
			var cb = _g[2];
			this.pausedCallback = haxe_ds_Option.None;
			cb(this.fakeTime);
			break;
		case 1:
			break;
		}
	}
	,keyup: function(callback) {
		var _gthis = this;
		this.keyupHandler = callback;
		window.onkeyup = function(key) {
			_gthis.onKey(key.keyCode,false);
		};
	}
	,keydown: function(callback) {
		var _gthis = this;
		this.keydownHandler = callback;
		window.onkeydown = function(key) {
			_gthis.onKey(key.keyCode,true);
		};
	}
	,onKey: function(keyCode,down) {
		this.sendGameInput(keyCode,down);
		if(down) {
			this.handleInterfaceInput(keyCode);
		}
	}
	,sendGameInput: function(keyCode,down) {
		this.recording.recordKey(this.control.frame,keyCode,down);
		var event = { which : keyCode, preventDefault : function() {
		}};
		if(down) {
			this.keydownHandler(event);
		} else {
			this.keyupHandler(event);
		}
	}
	,handleInterfaceInput: function(keyCode) {
		if(keyCode == 90 && this.control.paused) {
			this.triggerPausedCallback();
		}
		if(keyCode == 81) {
			this.control.paused = !this.control.paused;
			if(!this.control.paused) {
				this.triggerPausedCallback();
			}
		}
		if(keyCode == 82) {
			console.log("level replay string: " + this.recording.video.toString());
			this.recording = new VideoRecorder();
			this.control = new PlayControl();
			this.playback = haxe_ds_Option.Some(new VideoPlayer(new Video("uAAA22nACvUwIIHZGW4IFYYZJUqoLIaUGAYrYKKDJBCWDAYqoQAxBAzRAhVEAYlodlpclBKJbJ")));
			this.triggerPausedCallback();
		}
	}
	,__class__: Engine
};
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	var engine = new Engine();
};
Math.__name__ = true;
var Video = function(save) {
	this.actions = [];
	if(save != null) {
		var reader = new BSReader(save);
		var saveSize = this.getOption(reader.readInt(Video.headerSize));
		var frame = 0;
		var _g1 = 0;
		var _g = saveSize;
		while(_g1 < _g) {
			var i = _g1++;
			var longDelay = this.getOption(reader.read(1))[0];
			var delay = this.getOption(reader.readInt(longDelay ? Video.longDelaySize : Video.delaySize));
			var code = this.getOption(reader.readInt(2));
			var down = this.getOption(reader.read(1));
			frame += delay;
			this.actions.push({ frame : frame, code : code, down : down[0]});
		}
	}
};
Video.__name__ = true;
Video.toActionCode = function(keyCode) {
	var _g = 0;
	while(_g < 4) {
		var i = _g++;
		if(Video.keyCodes[i] == keyCode) {
			return haxe_ds_Option.Some(i);
		}
	}
	return haxe_ds_Option.None;
};
Video.fromActionCode = function(actionCode) {
	return Video.keyCodes[actionCode];
};
Video.showActionCode = function(actionCode) {
	switch(actionCode) {
	case 0:
		return "left";
	case 1:
		return "jump";
	case 2:
		return "right";
	case 3:
		return "axe";
	}
	return "???";
};
Video.prototype = {
	getOption: function(x) {
		switch(x[1]) {
		case 0:
			var x1 = x[2];
			return x1;
		case 1:
			throw new js__$Boot_HaxeError("Invalid video string.");
			break;
		}
	}
	,toString: function() {
		var writer = new BSWriter();
		writer.writeInt(this.actions.length,Video.headerSize);
		var lastFrame = 0;
		var _g = 0;
		var _g1 = this.actions;
		while(_g < _g1.length) {
			var action = _g1[_g];
			++_g;
			var delay = action.frame - lastFrame;
			lastFrame = action.frame;
			var longDelay = delay >= 32;
			writer.write([longDelay]);
			writer.writeInt(delay,longDelay ? Video.longDelaySize : Video.delaySize);
			writer.writeInt(action.code,2);
			writer.write([action.down]);
		}
		return writer.toString();
	}
	,__class__: Video
};
var VideoRecorder = function() {
	this.video = new Video();
	this.keyStates = [];
	var _g1 = 0;
	var _g = Video.keyCodes.length;
	while(_g1 < _g) {
		var i = _g1++;
		this.keyStates.push(false);
	}
};
VideoRecorder.__name__ = true;
VideoRecorder.prototype = {
	recordKey: function(frame,keyCode,down) {
		var _g = Video.toActionCode(keyCode);
		switch(_g[1]) {
		case 0:
			var action = _g[2];
			var oldState = this.keyStates[action];
			if(down == oldState) {
				return;
			}
			this.keyStates[action] = down;
			this.video.actions.push({ frame : frame, code : action, down : down});
			console.log("" + Video.showActionCode(action) + " " + (down ? "down" : "up") + " on frame " + frame);
			break;
		case 1:
			return;
		}
	}
	,__class__: VideoRecorder
};
var VideoPlayer = function(video) {
	this.actions = video.actions.slice();
};
VideoPlayer.__name__ = true;
VideoPlayer.prototype = {
	getActions: function(frame) {
		var res = [];
		while(this.actions.length > 0 && this.actions[0].frame == frame) {
			var action = this.actions.shift();
			res.push({ code : Video.fromActionCode(action.code), down : action.down});
		}
		return res;
	}
	,done: function(frame) {
		if(this.actions.length != 0) {
			return this.actions[0].frame < frame;
		} else {
			return true;
		}
	}
	,__class__: VideoPlayer
};
var haxe_crypto_Base64 = function() { };
haxe_crypto_Base64.__name__ = true;
var haxe_ds_Option = { __ename__ : true, __constructs__ : ["Some","None"] };
haxe_ds_Option.Some = function(v) { var $x = ["Some",0,v]; $x.__enum__ = haxe_ds_Option; return $x; };
haxe_ds_Option.None = ["None",1];
haxe_ds_Option.None.__enum__ = haxe_ds_Option;
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
String.prototype.__class__ = String;
String.__name__ = true;
Array.__name__ = true;
Video.headerSize = 24;
Video.delaySize = 5;
Video.longDelaySize = 10;
Video.keyCodes = [37,38,39,88];
haxe_crypto_Base64.CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
